File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/__init__.py, line 216, in _prepareconfig
    197  def _prepareconfig(args=None, plugins=None):
 (...)
    212                      pluginmanager.consider_pluginarg(plugin)
    213                  else:
    214                      pluginmanager.register(plugin)
    215          try:
--> 216            return pluginmanager.hook.pytest_cmdline_parse(
    217                pluginmanager=pluginmanager, args=args
    ..................................................
     args = ['--doctest-modules', '--showlocals', '--debug', '--full-tra
             ce', '--trace', '--show-locals', ]
     plugins = None
     pluginmanager.consider_pluginarg = <method 'PytestPluginManager.consider_pluginarg' of <_pytest
                                         .config.PytestPluginManager object at 0x10fdcd190> __init__.
                                         py:508>
     pluginmanager.register = <method 'PytestPluginManager.register' of <_pytest.config.Py
                               testPluginManager object at 0x10fdcd190> __init__.py:329>
     pluginmanager.hook.pytest_cmdline_parse = <_HookCaller 'pytest_cmdline_parse'>
     pluginmanager = <_pytest.config.PytestPluginManager object at 0x10fdcd190>
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/hooks.py, line 286, in __call__
    272  def __call__(self, *args, **kwargs):
 (...)
    282                  "Argument(s) {} which are declared in the hookspec "
    283                  "can not be found in this hook call".format(tuple(notincall)),
    284                  stacklevel=2,
    285              )
--> 286      return self._hookexec(self, self.get_hookimpls(), kwargs)
    ..................................................
     self = <_HookCaller 'pytest_cmdline_parse'>
     args = ()
     kwargs = {'pluginmanager': <_pytest.config.PytestPluginManager object
                at 0x10fdcd190>,
               'args': ['--doctest-modules', '--showlocals', '--debug', '-
               -full-trace', '--trace', '--show-locals', ]}
     notincall = {}
     self._hookexec = <method 'PluginManager._hookexec' of <_pytest.config.PytestP
                       luginManager object at 0x10fdcd190> manager.py:89>
     self.get_hookimpls = <method '_HookCaller.get_hookimpls' of <_HookCaller 'pytest_
                           cmdline_parse'> hooks.py:238>
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/manager.py, line 92, in _hookexec
    89   def _hookexec(self, hook, methods, kwargs):
    90       # called from all hookcaller instances.
    91       # enable_tracing will set its own wrapping function at self._inner_hookexec
--> 92       return self._inner_hookexec(hook, methods, kwargs)
    ..................................................
     self = <_pytest.config.PytestPluginManager object at 0x10fdcd190>
     hook = <_HookCaller 'pytest_cmdline_parse'>
     methods = [<HookImpl plugin_name='pytestconfig', plugin=<_pytest.confi
                g.Config object at 0x10fe88a60>>, <HookImpl plugin_name='hel
                pconfig', plugin=<module '_pytest.helpconfig' from '/Users/a
                lberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages
                /_pytest/helpconfig.py'>>, ]
     kwargs = {'pluginmanager': <_pytest.config.PytestPluginManager object
                at 0x10fdcd190>,
               'args': ['--doctest-modules', '--showlocals', '--debug', '-
               -full-trace', '--trace', '--show-locals', ]}
     self._inner_hookexec = <function 'PluginManager.__init__.<locals>.<lambda>' manager
                             .py:83>
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/manager.py, line 83, in <lambda>
    79           DeprecationWarning,
    80           stacklevel=2,
    81       )
    82   self._implprefix = implprefix
--> 83   self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
    84       methods,
    ..................................................
     hook = <_HookCaller 'pytest_cmdline_parse'>
     methods = [<HookImpl plugin_name='pytestconfig', plugin=<_pytest.confi
                g.Config object at 0x10fe88a60>>, <HookImpl plugin_name='hel
                pconfig', plugin=<module '_pytest.helpconfig' from '/Users/a
                lberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages
                /_pytest/helpconfig.py'>>, ]
     kwargs = {'pluginmanager': <_pytest.config.PytestPluginManager object
                at 0x10fdcd190>,
               'args': ['--doctest-modules', '--showlocals', '--debug', '-
               -full-trace', '--trace', '--show-locals', ]}
     hook.multicall = <function '_multicall' callers.py:157>
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/callers.py, line 203, in _multicall
    157  def _multicall(hook_impls, caller_kwargs, firstresult=False):
 (...)
    199  
    200          # run all wrapper post-yield blocks
    201          for gen in reversed(teardowns):
    202              try:
--> 203                  gen.send(outcome)
    204                  _raise_wrapfail(gen, "has second yield")
    ..................................................
     hook_impls = [<HookImpl plugin_name='pytestconfig', plugin=<_pytest.confi
                   g.Config object at 0x10fe88a60>>, <HookImpl plugin_name='hel
                   pconfig', plugin=<module '_pytest.helpconfig' from '/Users/a
                   lberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages
                   /_pytest/helpconfig.py'>>, ]
     caller_kwargs = {'pluginmanager': <_pytest.config.PytestPluginManager object
                       at 0x10fdcd190>,
                      'args': ['--doctest-modules', '--showlocals', '--debug', '-
                      -full-trace', '--trace', '--show-locals', ]}
     firstresult = True
     gen = <generator object pytest_cmdline_parse at 0x10ff8d970>
     teardowns = [<generator object pytest_cmdline_parse at 0x10ff8d970>, ]
     outcome = <pluggy.callers._Result object at 0x10fe95130>
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/helpconfig.py, line 89, in pytest_cmdline_parse
    86   @pytest.hookimpl(hookwrapper=True)
    87   def pytest_cmdline_parse():
    88       outcome = yield
--> 89       config = outcome.get_result()
    90       if config.option.debug:
    ..................................................
     pytest.hookimpl = <pluggy.hooks.HookimplMarker object at 0x10f1cff10>
     outcome = <pluggy.callers._Result object at 0x10fe95130>
     outcome.get_result = <method '_Result.get_result' of <pluggy.callers._Result obje
                           ct at 0x10fe95130> callers.py:68>
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/callers.py, line 80, in get_result
    68   def get_result(self):
 (...)
    76           return self._result
    77       else:
    78           ex = self._excinfo
    79           if _py3:
--> 80               raise ex[1].with_traceback(ex[2])
    81           _reraise(*ex)  # noqa
    ..................................................
     self = <pluggy.callers._Result object at 0x10fe95130>
     self._result = None
     ex = (<class '_pytest.config.exceptions.UsageError'>, UsageError(
           'usage: pytest [options] [file_or_dir] [file_or_dir] [...]\n
           pytest: error: unrecognized arguments: --show-locals\n  inif
           ile: /Users/alberthan/VSCodeProjects/hdlogger/pytest.ini\n  
           rootdir: /Users/alberthan/VSCodeProjects/hdlogger'), <traceb
           ack object at 0x11012f540>, )
     self._excinfo = (<class '_pytest.config.exceptions.UsageError'>, UsageError(
                      'usage: pytest [options] [file_or_dir] [file_or_dir] [...]\n
                      pytest: error: unrecognized arguments: --show-locals\n  inif
                      ile: /Users/alberthan/VSCodeProjects/hdlogger/pytest.ini\n  
                      rootdir: /Users/alberthan/VSCodeProjects/hdlogger'), <traceb
                      ack object at 0x11012f540>, )
     _py3 = True
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/callers.py, line 187, in _multicall
    157  def _multicall(hook_impls, caller_kwargs, firstresult=False):
 (...)
    183                          teardowns.append(gen)
    184                      except StopIteration:
    185                          _raise_wrapfail(gen, "did not yield")
    186                  else:
--> 187                      res = hook_impl.function(*args)
    188                      if res is not None:
    ..................................................
     hook_impls = [<HookImpl plugin_name='pytestconfig', plugin=<_pytest.confi
                   g.Config object at 0x10fe88a60>>, <HookImpl plugin_name='hel
                   pconfig', plugin=<module '_pytest.helpconfig' from '/Users/a
                   lberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages
                   /_pytest/helpconfig.py'>>, ]
     caller_kwargs = {'pluginmanager': <_pytest.config.PytestPluginManager object
                       at 0x10fdcd190>,
                      'args': ['--doctest-modules', '--showlocals', '--debug', '-
                      -full-trace', '--trace', '--show-locals', ]}
     firstresult = True
     gen = <generator object pytest_cmdline_parse at 0x10ff8d970>
     hook_impl.function = <method 'Config.pytest_cmdline_parse' of <_pytest.config.Con
                           fig object at 0x10fe88a60> __init__.py:736>
     args = [<_pytest.config.PytestPluginManager object at 0x10fdcd190>,
              ['--doctest-modules', '--showlocals', '--debug', '--full-tr
             ace', '--trace', '--show-locals', ], ]
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/__init__.py, line 738, in pytest_cmdline_parse
    736  def pytest_cmdline_parse(self, pluginmanager, args):
    737      try:
--> 738          self.parse(args)
    739      except UsageError:
    ..................................................
     self = <_pytest.config.Config object at 0x10fe88a60>
     pluginmanager = <_pytest.config.PytestPluginManager object at 0x10fdcd190>
     args = ['--doctest-modules', '--showlocals', '--debug', '--full-tra
             ce', '--trace', '--show-locals', ]
     self.parse = <method 'Config.parse' of <_pytest.config.Config object at 0
                   x10fe88a60> __init__.py:936>
     UsageError = <class '_pytest.config.exceptions.UsageError'>
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/__init__.py, line 950, in parse
    936  def parse(self, args, addopts=True):
 (...)
    946      # XXX deprecated hook:
    947      self.hook.pytest_cmdline_preparse(config=self, args=args)
    948      self._parser.after_preparse = True
    949      try:
--> 950          args = self._parser.parse_setoption(
    951              args, self.option, namespace=self.option
    ..................................................
     self = <_pytest.config.Config object at 0x10fe88a60>
     args = ['--doctest-modules', '--showlocals', '--debug', '--full-tra
             ce', '--trace', '--show-locals', ]
     addopts = True
     self.hook.pytest_cmdline_preparse = <_HookCaller 'pytest_cmdline_preparse'>
     self._parser.after_preparse = True
     self._parser.parse_setoption = <method 'Parser.parse_setoption' of <_pytest.config.argparsi
                                     ng.Parser object at 0x10fe88af0> argparsing.py:108>
     self.option = Namespace(assertmode='rewrite', basetemp=None, cacheclear=Fa
                    lse, cacheshow=None, capture='fd', collect_in_virtualenv=Fal
                    se, collectonly=False, color='auto', confcutdir=None, contin
                    ue_on_collection_errors=False, debug=True, deselect=None, di
                    sable_warnings=False, doctest_continue_on_failure=False, doc
                    test_ignore_import_errors=False, doctestglob=[], doctestmodu
                    les=True, doctestreport='udiff', durations=None, failedfirst
                    =False, file_or_dir=[], fulltrace=True, help=False, ignore=N
                    one, ignore_glob=Non...
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/argparsing.py, line 109, in parse_setoption
    108  def parse_setoption(self, args, option, namespace=None):
--> 109      parsedoption = self.parse(args, namespace=namespace)
    110      for name, value in parsedoption.__dict__.items():
    ..................................................
     self = <_pytest.config.argparsing.Parser object at 0x10fe88af0>
     args = ['--doctest-modules', '--showlocals', '--debug', '--full-tra
             ce', '--trace', '--show-locals', ]
     option = Namespace(assertmode='rewrite', basetemp=None, cacheclear=Fa
               lse, cacheshow=None, capture='fd', collect_in_virtualenv=Fal
               se, collectonly=False, color='auto', confcutdir=None, contin
               ue_on_collection_errors=False, debug=True, deselect=None, di
               sable_warnings=False, doctest_continue_on_failure=False, doc
               test_ignore_import_errors=False, doctestglob=[], doctestmodu
               les=True, doctestreport='udiff', durations=None, failedfirst
               =False, file_or_dir=[], fulltrace=True, help=False, ignore=N
               one, ignore_glob=Non...
     namespace = Namespace(assertmode='rewrite', basetemp=None, cacheclear=Fa
                  lse, cacheshow=None, capture='fd', collect_in_virtualenv=Fal
                  se, collectonly=False, color='auto', confcutdir=None, contin
                  ue_on_collection_errors=False, debug=True, deselect=None, di
                  sable_warnings=False, doctest_continue_on_failure=False, doc
                  test_ignore_import_errors=False, doctestglob=[], doctestmodu
                  les=True, doctestreport='udiff', durations=None, failedfirst
                  =False, file_or_dir=[], fulltrace=True, help=False, ignore=N
                  one, ignore_glob=Non...
     self.parse = <method 'Parser.parse' of <_pytest.config.argparsing.Parser 
                   object at 0x10fe88af0> argparsing.py:80>
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/argparsing.py, line 86, in parse
    80   def parse(self, args, namespace=None):
 (...)
    82   
    83       self.optparser = self._getparser()
    84       try_argcomplete(self.optparser)
    85       args = [str(x) if isinstance(x, py.path.local) else x for x in args]
--> 86       return self.optparser.parse_args(args, namespace=namespace)
    ..................................................
     self = <_pytest.config.argparsing.Parser object at 0x10fe88af0>
     args = ['--doctest-modules', '--showlocals', '--debug', '--full-tra
             ce', '--trace', '--show-locals', ]
     namespace = Namespace(assertmode='rewrite', basetemp=None, cacheclear=Fa
                  lse, cacheshow=None, capture='fd', collect_in_virtualenv=Fal
                  se, collectonly=False, color='auto', confcutdir=None, contin
                  ue_on_collection_errors=False, debug=True, deselect=None, di
                  sable_warnings=False, doctest_continue_on_failure=False, doc
                  test_ignore_import_errors=False, doctestglob=[], doctestmodu
                  les=True, doctestreport='udiff', durations=None, failedfirst
                  =False, file_or_dir=[], fulltrace=True, help=False, ignore=N
                  one, ignore_glob=Non...
     self.optparser = MyOptionParser(prog='pytest', usage='%(prog)s [options] [fil
                       e_or_dir] [file_or_dir] [...]', description=None, formatter_
                       class=<class '_pytest.config.argparsing.DropShorterLongHelpF
                       ormatter'>, conflict_handler='error', add_help=False)
     self._getparser = <method 'Parser._getparser' of <_pytest.config.argparsing.Pa
                        rser object at 0x10fe88af0> argparsing.py:88>
     py.path.local = <class 'py._path.local.LocalPath'>
     self.optparser.parse_args = <method 'MyOptionParser.parse_args' of MyOptionParser(prog='
                                  pytest', usage='%(prog)s [options] [file_or_dir] [file_or_di
                                  r] [...]', description=None, formatter_class=<class '_pytest
                                  .config.argparsing.DropShorterLongHelpFormatter'>, conflict_
                                  handler='error', add_help=False) argparsing.py:358>
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/argparsing.py, line 367, in parse_args
    358  def parse_args(self, args=None, namespace=None):
 (...)
    363              if arg and arg[0] == "-":
    364                  lines = ["unrecognized arguments: %s" % (" ".join(argv))]
    365                  for k, v in sorted(self.extra_info.items()):
    366                      lines.append("  {}: {}".format(k, v))
--> 367                  self.error("\n".join(lines))
    368          getattr(args, FILE_OR_DIR).extend(argv)
    ..................................................
     self = MyOptionParser(prog='pytest', usage='%(prog)s [options] [fil
             e_or_dir] [file_or_dir] [...]', description=None, formatter_
             class=<class '_pytest.config.argparsing.DropShorterLongHelpF
             ormatter'>, conflict_handler='error', add_help=False)
     args = Namespace(assertmode='rewrite', basetemp=None, cacheclear=Fa
             lse, cacheshow=None, capture='fd', collect_in_virtualenv=Fal
             se, collectonly=False, color='auto', confcutdir=None, contin
             ue_on_collection_errors=False, debug=True, deselect=None, di
             sable_warnings=False, doctest_continue_on_failure=False, doc
             test_ignore_import_errors=False, doctestglob=[], doctestmodu
             les=True, doctestreport='udiff', durations=None, failedfirst
             =False, file_or_dir=[], fulltrace=True, help=False, ignore=N
             one, ignore_glob=Non...
     namespace = Namespace(assertmode='rewrite', basetemp=None, cacheclear=Fa
                  lse, cacheshow=None, capture='fd', collect_in_virtualenv=Fal
                  se, collectonly=False, color='auto', confcutdir=None, contin
                  ue_on_collection_errors=False, debug=True, deselect=None, di
                  sable_warnings=False, doctest_continue_on_failure=False, doc
                  test_ignore_import_errors=False, doctestglob=[], doctestmodu
                  les=True, doctestreport='udiff', durations=None, failedfirst
                  =False, file_or_dir=[], fulltrace=True, help=False, ignore=N
                  one, ignore_glob=Non...
     arg = '--show-locals'
     lines = ['unrecognized arguments: --show-locals', '  inifile: /Users
              /alberthan/VSCodeProjects/hdlogger/pytest.ini', '  rootdir: 
              /Users/alberthan/VSCodeProjects/hdlogger', ]
     argv = ['--show-locals', ]
     k = 'rootdir'
     v = local('/Users/alberthan/VSCodeProjects/hdlogger')
     self.error = <method 'MyOptionParser.error' of MyOptionParser(prog='pytes
                   t', usage='%(prog)s [options] [file_or_dir] [file_or_dir] [.
                   ..]', description=None, formatter_class=<class '_pytest.conf
                   ig.argparsing.DropShorterLongHelpFormatter'>, conflict_handl
                   er='error', add_help=False) argparsing.py:349>
     FILE_OR_DIR = 'file_or_dir'
    ..................................................

File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/argparsing.py, line 356, in error
    349  def error(self, message):
 (...)
    352  
    353      if hasattr(self._parser, "_config_source_hint"):
    354          msg = "{} ({})".format(msg, self._parser._config_source_hint)
    355  
--> 356      raise UsageError(self.format_usage() + msg)
    ..................................................
     self = MyOptionParser(prog='pytest', usage='%(prog)s [options] [fil
             e_or_dir] [file_or_dir] [...]', description=None, formatter_
             class=<class '_pytest.config.argparsing.DropShorterLongHelpF
             ormatter'>, conflict_handler='error', add_help=False)
     message = 'unrecognized arguments: --show-locals\n  inifile: /Users/al
                berthan/VSCodeProjects/hdlogger/pytest.ini\n  rootdir: /User
                s/alberthan/VSCodeProjects/hdlogger'
     self._parser = <_pytest.config.argparsing.Parser object at 0x10fe88af0>
     msg = 'pytest: error: unrecognized arguments: --show-locals\n  ini
            file: /Users/alberthan/VSCodeProjects/hdlogger/pytest.ini\n 
             rootdir: /Users/alberthan/VSCodeProjects/hdlogger'
     self._parser._config_source_hint = # AttributeError
          self._parser = <_pytest.config.argparsing.Parser object at 0
           x10fe88af0>
     UsageError = <class '_pytest.config.exceptions.UsageError'>
     self.format_usage = <method 'ArgumentParser.format_usage' of MyOptionParser(prog
                          ='pytest', usage='%(prog)s [options] [file_or_dir] [file_or_
                          dir] [...]', description=None, formatter_class=<class '_pyte
                          st.config.argparsing.DropShorterLongHelpFormatter'>, conflic
                          t_handler='error', add_help=False) argparse.py:2439>
    ..................................................

---- (full traceback above) ----
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/__init__.py, line 216, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/hooks.py, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/manager.py, line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/manager.py, line 83, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/callers.py, line 203, in _multicall
    gen.send(outcome)
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/helpconfig.py, line 89, in pytest_cmdline_parse
    config = outcome.get_result()
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/callers.py, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/pluggy/callers.py, line 187, in _multicall
    res = hook_impl.function(*args)
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/__init__.py, line 738, in pytest_cmdline_parse
    self.parse(args)
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/__init__.py, line 950, in parse
    args = self._parser.parse_setoption(
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/argparsing.py, line 109, in parse_setoption
    parsedoption = self.parse(args, namespace=namespace)
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/argparsing.py, line 86, in parse
    return self.optparser.parse_args(args, namespace=namespace)
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/argparsing.py, line 367, in parse_args
    self.error("\n".join(lines))
File /Users/alberthan/VSCodeProjects/hdlogger/lib/python3.8/site-packages/_pytest/config/argparsing.py, line 356, in error
    raise UsageError(self.format_usage() + msg)

UsageError: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --show-locals
  inifile: /Users/alberthan/VSCodeProjects/hdlogger/pytest.ini
  rootdir: /Users/alberthan/VSCodeProjects/hdlogger
