from pydantic import BaseModel


class TraceHookCallbackException(BaseModel):
  klass:
     self._arg = (<class 'KeyError'>, KeyError(b'LANGUAGE'), <traceback objec
                  t at 0x11317f380>, )
