from pydantic import BaseModel


class TraceHookCallbackException(BaseModel):
  klass: "self._arg = (<class 'KeyError'>, KeyError(b'LANGUAGE'), <traceback object at 0x11317f380>, )"


  def
